[project]
name = "url_fetcher"
description = "Fetches URLs"
version = "1.0.2"
license = {file = "LICENSE"}
dependencies = ["requests"]

[project.urls]
Repository = "https://github.com/molbal/comfy-url-fetcher"

[tool.comfy]
PublisherId = "molbal"
DisplayName = "URL Fetcher"
Icon = ""